version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./nginx_proxy/data:/data
      - ./nginx_proxy/letsencrypt:/etc/letsencrypt

  goaccess:
    image: 'xavierh/goaccess-for-nginxproxymanager:latest'
    container_name: goaccess
    restart: always
    ports:
      - '7880:7880'
    environment:
      - TZ=UTC
    volumes:
      - ./nginx_proxy/data/logs:/opt/log